[Features]
	coloredCobblestone = false
	darkGlass = false
	smoothGlowstone = false
	wateringCan = false
	meshes = false
	magnet = false
	nightVisionGoggles = false
	paxels = false
	flintGear = false
	emeraldGear = false
	rightClickHarvest = false
["Grid Repair"]
	enabled = false
[Tweaks]
	toolBreaking = false
	