[policy]
	[policy.mob]
		spawnTicks = ["minecraft:wither,1200", "minecraft:ender_dragon,12000", "botania:doppleganger,12000"]
		tier = ["minecraft:wither_skeleton,4", "minecraft:villager,4", "minecraft:magma_cube,3", "minecraft:enderman,4", "minecraft:villager_golem,4", "minecraft:guardian,4", "minecraft:blaze,3", "minecraft:witch,3", "minecraft:ghast,3", "minecraft:zombie_pigman,3", "minecraft:ender_dragon,5", "minecraft:wither,5", "botania:doppleganger,5"]
		xp = ["minecraft:iron_golem,20", "minecraft:bat,1", "minecraft:snow_golem,1", "minecraft:villager,2", "minecraft:wandering_villager,2", "minecraft:ender_dragon,500", "botania:doppleganger,1"]
		health = ["minecraft:ender_dragon,500", "botania:doppleganger,250"]
		customDropsOnly = ["minecraft:ender_dragon", "botania:doppleganger"]
		[policy.mob.perk]
			mass1 = ["minecraft:ender_dragon,2", "minecraft:wither,2", "botania:doppleganger,2"]
			mass2 = ["minecraft:ender_dragon,3", "minecraft:wither,3", "botania:doppleganger,3"]
			mass3 = ["minecraft:ender_dragon,4", "minecraft:wither,4", "botania:doppleganger,4"]
	[policy.blacklist]
		captureMod = []
